/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.orders;

import controller.ReturnController;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Return;
import model.ReturnDetail;
import swing.UIController;

public class ReturnDetailDialog extends javax.swing.JDialog {
    
    private ReturnController rc;
    
    /**
     * Creates new form ImportHistoryDialog
     *
     * @param parent
     * @param modal
     */
    public ReturnDetailDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        
        rc = new ReturnController();
        Return return0 = rc.getReturnByOrderId(OrderPanel.orderId);
        List<ReturnDetail> detail = rc.getReturnDetailByReturnId(return0.getId());
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        NumberFormat numberFormat = new DecimalFormat("###,###");
        jLabel_ID.setText(return0.getId() + "");
        jLabel_Date.setText(sdf.format(return0.getDate()));
        jLabel_RefundType.setText(return0.getRefundType());
        jLabel_TotalPrice.setText(numberFormat.format(return0.getTotalPrice()));
        jLabel_OrderID.setText(OrderPanel.orderId + "");
        jLabel_Reason.setText("<html>" + return0.getReason() + "</html>");
        jLabel_Status.setText((return0.getIsApproved() == null) ? "Proccessing" : ((return0.getIsApproved() == true) ? "Approved" : "Unapproved"));
        
        UIController.setDefaultTableHeader(jTable_Product);
        
        rc.loadProductTable(detail, (DefaultTableModel) jTable_Product.getModel());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_ImportHistory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Product = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel_Gender1 = new javax.swing.JLabel();
        jLabel_Name1 = new javax.swing.JLabel();
        jLabel_Email1 = new javax.swing.JLabel();
        jLabel_Email2 = new javax.swing.JLabel();
        jLabel_Email3 = new javax.swing.JLabel();
        jLabel_Email4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_ID = new javax.swing.JLabel();
        jLabel_Date = new javax.swing.JLabel();
        jLabel_OrderID = new javax.swing.JLabel();
        jLabel_RefundType = new javax.swing.JLabel();
        jLabel_TotalPrice = new javax.swing.JLabel();
        jLabel_Status = new javax.swing.JLabel();
        jLabel_Reason = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel_ImportHistory.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_ImportHistory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ImportHistory.setText("Return Infomation");

        jTable_Product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Product Name", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Product);
        if (jTable_Product.getColumnModel().getColumnCount() > 0) {
            jTable_Product.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable_Product.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Return information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14), new java.awt.Color(153, 153, 153))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridLayout(6, 1, 0, 10));

        jLabel_Gender1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_Gender1.setText("ID:");
        jPanel5.add(jLabel_Gender1);

        jLabel_Name1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_Name1.setText("Date:");
        jPanel5.add(jLabel_Name1);

        jLabel_Email1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_Email1.setText("Order ID:");
        jPanel5.add(jLabel_Email1);

        jLabel_Email2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_Email2.setText("Refund Type:");
        jPanel5.add(jLabel_Email2);

        jLabel_Email3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_Email3.setText("Total Price:");
        jPanel5.add(jLabel_Email3);

        jLabel_Email4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_Email4.setText("Status:");
        jPanel5.add(jLabel_Email4);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 100, 250));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(6, 1, 0, 10));

        jLabel_ID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_ID.setText("ID");
        jPanel3.add(jLabel_ID);

        jLabel_Date.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_Date.setText("Date");
        jPanel3.add(jLabel_Date);

        jLabel_OrderID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_OrderID.setText("Order ID");
        jPanel3.add(jLabel_OrderID);

        jLabel_RefundType.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_RefundType.setText("Refund Type");
        jPanel3.add(jLabel_RefundType);

        jLabel_TotalPrice.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_TotalPrice.setText("Total Price");
        jPanel3.add(jLabel_TotalPrice);

        jLabel_Status.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_Status.setText("Status");
        jPanel3.add(jLabel_Status);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 5, 550, 250));

        jLabel_Reason.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_Reason.setText("...");
        jLabel_Reason.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Reason:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Reason, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Reason, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel_ImportHistory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_ImportHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReturnDetailDialog dialog = new ReturnDetailDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_Date;
    private javax.swing.JLabel jLabel_Email1;
    private javax.swing.JLabel jLabel_Email2;
    private javax.swing.JLabel jLabel_Email3;
    private javax.swing.JLabel jLabel_Email4;
    private javax.swing.JLabel jLabel_Gender1;
    private javax.swing.JLabel jLabel_ID;
    private javax.swing.JLabel jLabel_ImportHistory;
    private javax.swing.JLabel jLabel_Name1;
    private javax.swing.JLabel jLabel_OrderID;
    private javax.swing.JLabel jLabel_Reason;
    private javax.swing.JLabel jLabel_RefundType;
    private javax.swing.JLabel jLabel_Status;
    private javax.swing.JLabel jLabel_TotalPrice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Product;
    // End of variables declaration//GEN-END:variables
}
