/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.profile;

import controller.UserController;
import java.awt.Image;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Response;
import model.UserDB;
import okhttp3.MediaType;
import okhttp3.MultipartBody;
import okhttp3.RequestBody;
import okhttp3.ResponseBody;
import retrofit2.Call;
import retrofit2.Callback;
import service.APIClient;
import service.UploadFileService;
import view.login.LoginFrame;

/**
 *
 * @author Admin
 */
public class ProfilePanel extends javax.swing.JPanel {

    public static final Pattern VALID_EMAIL_ADDRESS_REGEX = Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);
    public static final Pattern VALID_PHONE_NUMBER_REGEX = Pattern.compile("^(0?)(3[2-9]|5[6|8|9]|7[0|6-9]|8[0-6|8|9]|9[0-4|6-9])[0-9]{7}$", Pattern.CASE_INSENSITIVE);
    private static final String FULLNAME_PATTERN
            = "^[a-zA-Z_ÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶ"
            + "ẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợ"
            + "ụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ\\s]+$";
    private UserController uc;
    private PasswordChangeDialog passwordChangeDialog;
    private AddressChangeDialog addressChangeDialog;
    private UserDB u;
    private String imageName;
    private File selectedFile;

    /**
     * Creates new form ProfilePanel
     */
    public ProfilePanel() {
        initComponents();
        uc = new UserController();
        u = uc.getUserById(String.valueOf(LoginFrame.userID));
        loadUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_EditProfile = new javax.swing.JButton();
        jButton_ChangePass = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_LastName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_PhoneNumber = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField_FirstName = new javax.swing.JTextField();
        jLabel_Img = new javax.swing.JLabel();
        jButton_Change = new javax.swing.JButton();
        jButton_ChangeAddress = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton_EditProfile.setBackground(new java.awt.Color(51, 153, 255));
        jButton_EditProfile.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton_EditProfile.setForeground(new java.awt.Color(255, 255, 255));
        jButton_EditProfile.setText("Save");
        jButton_EditProfile.setBorderPainted(false);
        jButton_EditProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_EditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditProfileActionPerformed(evt);
            }
        });

        jButton_ChangePass.setBackground(new java.awt.Color(51, 153, 255));
        jButton_ChangePass.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton_ChangePass.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ChangePass.setText("Change password");
        jButton_ChangePass.setBorderPainted(false);
        jButton_ChangePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_ChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChangePassActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Username");

        jTextField_Username.setEditable(false);
        jTextField_Username.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Last name");

        jTextField_LastName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Phone number");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("Email");

        jTextField_PhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jTextField_Email.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel12.setText("First name");

        jTextField_FirstName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel_Img.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel_Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/User_256px.png"))); // NOI18N

        jButton_Change.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jButton_Change.setText("Change");
        jButton_Change.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChangeActionPerformed(evt);
            }
        });

        jButton_ChangeAddress.setBackground(new java.awt.Color(51, 153, 255));
        jButton_ChangeAddress.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton_ChangeAddress.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ChangeAddress.setText("Change address");
        jButton_ChangeAddress.setBorderPainted(false);
        jButton_ChangeAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_ChangeAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChangeAddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel3))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_LastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel12)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_FirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(jTextField_PhoneNumber)
                            .addComponent(jTextField_Email))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_Change)
                        .addGap(241, 241, 241))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jButton_EditProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203)
                .addComponent(jButton_ChangeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(jButton_ChangePass)
                .addGap(220, 220, 220))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jTextField_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Change))
                .addGap(238, 238, 238)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ChangePass)
                    .addComponent(jButton_ChangeAddress)
                    .addComponent(jButton_EditProfile))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadUser() {
        jTextField_Username.setText(u.getUsername());
        jTextField_LastName.setText(u.getLastName());
        jTextField_FirstName.setText(u.getFirstName());
        jTextField_PhoneNumber.setText(u.getPhone());
        jTextField_Email.setText(u.getEmail());

        imageName = u.getImage();
        Image img = uc.getImage(imageName);
        System.out.println(jLabel_Img.getWidth() + "," + jLabel_Img.getHeight());
        Image newImg = img.getScaledInstance(256, 256, java.awt.Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(newImg);
        jLabel_Img.setIcon(icon);
    }

    public static boolean validate(String str, Pattern p) {
        Matcher matcher = p.matcher(str);
        return matcher.find();
    }

    public static boolean verifyName(String name) {
        if (name.equals("")) {
            return false;
        }
        return name.matches(FULLNAME_PATTERN);
    }

    private void jButton_ChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChangePassActionPerformed
        // TODO add your handling code here:
        this.passwordChangeDialog = new PasswordChangeDialog(null, true, u, this);
        this.passwordChangeDialog.setVisible(true);
    }//GEN-LAST:event_jButton_ChangePassActionPerformed

    private void jButton_EditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditProfileActionPerformed
        // TODO add your handling code here:
        UserDB user = new UserDB();
        user.setId(u.getId());
        user.setUsername(u.getUsername());
        user.setPassword(u.getPassword());
        user.setStatus(true);

        String email = jTextField_Email.getText();
        String phoneNumber = jTextField_PhoneNumber.getText();

        if (!verifyName(jTextField_FirstName.getText())) {
            JOptionPane.showMessageDialog(null, "Không được để trống\nKhông dùng ký tự đặc biệt", 
                    "Vui lòng nhập first name đúng định dạng sau", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!verifyName(jTextField_LastName.getText())) {
            JOptionPane.showMessageDialog(null, "Không được để trống\nKhông dùng ký tự đặc biệt", 
                    "Vui lòng nhập last name đúng định dạng sau", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!validate(email, VALID_EMAIL_ADDRESS_REGEX)) {
            JOptionPane.showMessageDialog(null, "Không được để trống\nSử dụng đúng định dạng Email chuẩn", 
                    "Vui lòng nhập email đúng định dạng", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!validate(phoneNumber, VALID_PHONE_NUMBER_REGEX)) {
            JOptionPane.showMessageDialog(null, "Không được để trống\nChỉ nhận kí tự số \nYêu cầu đủ 10 chữ số", 
                    "Vui lòng nhập số điện thoại đúng định dạng", JOptionPane.ERROR_MESSAGE);
            return;
        }

        user.setFirstName(jTextField_FirstName.getText());
        user.setLastName(jTextField_LastName.getText());
        user.setEmail(email);
        user.setPhone(phoneNumber);

        if (selectedFile != null) {
            try {
                RequestBody requestBody = RequestBody.create(MediaType.parse("multipart/form-data"), selectedFile);
                MultipartBody.Part part = MultipartBody.Part.createFormData("file", selectedFile.getName(), requestBody);
                UploadFileService uploadFileInterface = APIClient.getClient().create(UploadFileService.class);
                uploadFileInterface.uploadUserImage(part).enqueue(new Callback<ResponseBody>() {

                    @Override
                    public void onResponse(Call<ResponseBody> call, retrofit2.Response<ResponseBody> response) {
                        try {
                            if (response.isSuccessful()) {
                                String str = response.body().string();
                                user.setImage(str);
                                Response res = uc.updateUser(user);
                                JOptionPane.showMessageDialog(null, res.getMessage());
                                if (res.getResponseCode() == 200) {
                                    u = uc.getUserById(String.valueOf(LoginFrame.userID));
                                } else {
                                    return;
                                }
                            }
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e.getMessage());
                        }
                    }

                    @Override
                    public void onFailure(Call<ResponseBody> call, Throwable t) {
                        JOptionPane.showMessageDialog(null, t.getMessage());
                    }

                });
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else {
            user.setImage(imageName);
            Response response = uc.updateUser(user);
            JOptionPane.showMessageDialog(this, response.getMessage());
            if (response.getResponseCode() == 200) {
                u = uc.getUserById(String.valueOf(LoginFrame.userID));
            } else {
                return;
            }
        }
    }//GEN-LAST:event_jButton_EditProfileActionPerformed

    private void jButton_ChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChangeActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Image Files", "jpg", "png");
        fileChooser.setFileFilter(imageFilter);
        fileChooser.setMultiSelectionEnabled(false);
        int x = fileChooser.showDialog(this, "Select image");
        if (x == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();
            ImageIcon imgIcon = new ImageIcon(selectedFile.getAbsolutePath());
            Image img = imgIcon.getImage();
            Image newImg = img.getScaledInstance(jLabel_Img.getWidth(), jLabel_Img.getHeight(), java.awt.Image.SCALE_SMOOTH);
            jLabel_Img.setIcon(new ImageIcon(newImg));
            System.out.println(selectedFile.getName());
        } else {
            return;
        }
    }//GEN-LAST:event_jButton_ChangeActionPerformed

    private void jButton_ChangeAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChangeAddressActionPerformed
        // TODO add your handling code here:
        this.addressChangeDialog = new AddressChangeDialog(null, true, this);
        this.addressChangeDialog.setVisible(true);
    }//GEN-LAST:event_jButton_ChangeAddressActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Change;
    private javax.swing.JButton jButton_ChangeAddress;
    private javax.swing.JButton jButton_ChangePass;
    private javax.swing.JButton jButton_EditProfile;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_Img;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_FirstName;
    private javax.swing.JTextField jTextField_LastName;
    private javax.swing.JTextField jTextField_PhoneNumber;
    private javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables
}
