/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.promotion;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import model.Product;
import model.PromotionDetail;

public class ProductPromotionDialog extends javax.swing.JDialog {

    
    private JDialog parentPanel;
    private String productID;
    private String productName;

    /**
     * Creates new form importIngredientDialog
     */
    public ProductPromotionDialog(java.awt.Frame parent, boolean modal, /*Ingredient ingredient, */ JDialog parentPanel, String productID, String productName, Integer percentage) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
//        this.ingredient = ingredient;
        this.parentPanel = parentPanel;
//        loadData();
//        addSpinnerListener();

        this.productID = productID;
        this.productName = productName;
        jTextField_ID.setText(productID);
        jTextField_Name.setText(productName);
        jSpinner_Percentage.setValue(percentage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_ImportIngrTitle = new javax.swing.JLabel();
        jPanel_Info = new javax.swing.JPanel();
        jLabel_SelectIngr = new javax.swing.JLabel();
        jSpinner_Percentage = new javax.swing.JSpinner();
        jLabel_Amount = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jLabel_Unit = new javax.swing.JLabel();
        jButton_Cancel = new javax.swing.JButton();
        jButton_Save = new javax.swing.JButton();
        jLabel_ID = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel_ImportIngrTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_ImportIngrTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ImportIngrTitle.setText("Import Product");

        jPanel_Info.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Info.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_SelectIngr.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_SelectIngr.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_SelectIngr.setText("Name");

        jSpinner_Percentage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSpinner_Percentage.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel_Amount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_Amount.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_Amount.setText("Percentage");

        jTextField_Name.setEditable(false);
        jTextField_Name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel_Unit.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_Unit.setText("%");

        javax.swing.GroupLayout jPanel_InfoLayout = new javax.swing.GroupLayout(jPanel_Info);
        jPanel_Info.setLayout(jPanel_InfoLayout);
        jPanel_InfoLayout.setHorizontalGroup(
            jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_SelectIngr, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_InfoLayout.createSequentialGroup()
                        .addComponent(jSpinner_Percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Unit))
                    .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel_InfoLayout.setVerticalGroup(
            jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InfoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_SelectIngr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner_Percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Unit))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        jButton_Cancel.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jButton_Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        jButton_Cancel.setText("Cancel");
        jButton_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Cancel.setFocusPainted(false);
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });

        jButton_Save.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jButton_Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        jButton_Save.setText("Save");
        jButton_Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Save.setFocusPainted(false);
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });

        jLabel_ID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_ID.setText("ID");

        jTextField_ID.setEditable(false);
        jTextField_ID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_ImportIngrTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jButton_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(jButton_Cancel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(jLabel_ID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel_Info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_ImportIngrTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ID)
                    .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel_Info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Cancel)
                    .addComponent(jButton_Save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showErrorMessage(String message) {
        JOptionPane.showMessageDialog(null, message, "Application message", JOptionPane.ERROR_MESSAGE, new ImageIcon(getClass().getResource("/img/error.png")));
    }

    private void showInfoMessage(String message) {
        JOptionPane.showMessageDialog(null, message, "Application message", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/img/infor.png")));
    }

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveActionPerformed
        // TODO add your handling code here:
        int addQuantities = (int) jSpinner_Percentage.getValue();
        int percentage = Integer.parseInt(jSpinner_Percentage.getValue().toString());
        PromotionDetail detail = new PromotionDetail();
        detail.setProduct(new Product(Integer.parseInt(productID), productName));
        detail.setPercentage(percentage);

        if(NewPromotionDialog.isEdit == false) {
            NewPromotionDialog.promotionDetail.add(detail);
        }
        else {
            NewPromotionDialog.promotionDetail.add(detail);
            for(int i = 0; i < NewPromotionDialog.promotionDetail.size(); i++){
                if(NewPromotionDialog.promotionDetail.get(i).getProduct().getProductId() == Integer.parseInt(this.productID)){
                    NewPromotionDialog.promotionDetail.remove(i);
                }
            }
        }
        this.dispose();
    }//GEN-LAST:event_jButton_SaveActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Save;
    private javax.swing.JLabel jLabel_Amount;
    private javax.swing.JLabel jLabel_ID;
    private javax.swing.JLabel jLabel_ImportIngrTitle;
    private javax.swing.JLabel jLabel_SelectIngr;
    private javax.swing.JLabel jLabel_Unit;
    private javax.swing.JPanel jPanel_Info;
    private javax.swing.JSpinner jSpinner_Percentage;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_Name;
    // End of variables declaration//GEN-END:variables
}
