/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.promotion;

import view.imports.*;
import controller.ImportsController;
import controller.PromotionController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ImportDetail;
import model.Imports;
import model.Promotion;
import model.PromotionDetail;
import model.Response;
import swing.UIController;

/**
 *
 * @author HP
 */
public class PromotionPanel extends javax.swing.JPanel {

    private DefaultTableModel dtmPromotion;
    private DefaultTableModel dtmPromotionDetail;
    private PromotionController prc;
    private NewPromotionDialog newPromotionDialog;
    
    public PromotionPanel() {
        initComponents();
        prc = new PromotionController();
        dtmPromotionDetail = (DefaultTableModel) jTable_PromotionDetail.getModel();
        dtmPromotion = (DefaultTableModel) jTable_Promotion.getModel();
        UIController.setDefaultTableHeader(jTable_Promotion);
        UIController.setDefaultTableHeader(jTable_PromotionDetail);

        loadData("all");
    }
    
    public void loadData(String status) {
        List<Promotion> list = prc.getAllPromotions(status);
        prc.loadTable(list, dtmPromotion);
        jTextField_ID.setText("");
        jTextField_User.setText("");
        jTextField_StartDate.setText("");
        jTextField_FinishDate.setText("");
        dtmPromotionDetail.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel_ImportHistory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Promotion = new javax.swing.JTable();
        jPanel_BillDateInfo = new javax.swing.JPanel();
        jLabel_DayImportHistoryFrom = new javax.swing.JLabel();
        jLabel_DayImportHistoryTo = new javax.swing.JLabel();
        jDateChooser_StartDate = new com.toedter.calendar.JDateChooser();
        jDateChooser_FinishDate = new com.toedter.calendar.JDateChooser();
        jButton_Apply = new javax.swing.JButton();
        jButton_Clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Sum = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jTextField_User = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_StartDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_PromotionDetail = new javax.swing.JTable();
        jTextField_FinishDate = new javax.swing.JTextField();
        jPanel_Card1 = new javax.swing.JPanel();
        jButton_Add = new javax.swing.JButton();
        jButton_Modify = new javax.swing.JButton();
        jButton_Remove = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField_NameSearch = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton_All = new javax.swing.JRadioButton();
        jRadioButton_ComingSoon = new javax.swing.JRadioButton();
        jRadioButton_Ongoing = new javax.swing.JRadioButton();
        jRadioButton_Expired = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel_ImportHistory.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_ImportHistory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ImportHistory.setText("Promotion");

        jTable_Promotion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Start Date", "Finish Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Promotion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_PromotionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Promotion);

        jPanel_BillDateInfo.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_BillDateInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date filter", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14), new java.awt.Color(153, 153, 153))); // NOI18N

        jLabel_DayImportHistoryFrom.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_DayImportHistoryFrom.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_DayImportHistoryFrom.setText("From");

        jLabel_DayImportHistoryTo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_DayImportHistoryTo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_DayImportHistoryTo.setText("To");

        jDateChooser_StartDate.setDate(new java.util.Date());
        jDateChooser_StartDate.setDateFormatString("dd-MM-yyyy");
        jDateChooser_StartDate.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jDateChooser_FinishDate.setDate(new java.util.Date());
        jDateChooser_FinishDate.setDateFormatString("dd-MM-yyyy");
        jDateChooser_FinishDate.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jButton_Apply.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Apply.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Apply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tick3.png"))); // NOI18N
        jButton_Apply.setText("Apply");
        jButton_Apply.setFocusPainted(false);
        jButton_Apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ApplyActionPerformed(evt);
            }
        });

        jButton_Clear.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Clear.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel20px.png"))); // NOI18N
        jButton_Clear.setText("Clear");
        jButton_Clear.setFocusPainted(false);
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_BillDateInfoLayout = new javax.swing.GroupLayout(jPanel_BillDateInfo);
        jPanel_BillDateInfo.setLayout(jPanel_BillDateInfoLayout);
        jPanel_BillDateInfoLayout.setHorizontalGroup(
            jPanel_BillDateInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BillDateInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_BillDateInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_DayImportHistoryFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_DayImportHistoryTo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_BillDateInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jDateChooser_FinishDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser_StartDate, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addGap(80, 80, 80)
                .addGroup(jPanel_BillDateInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Apply, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_BillDateInfoLayout.setVerticalGroup(
            jPanel_BillDateInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BillDateInfoLayout.createSequentialGroup()
                .addGroup(jPanel_BillDateInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_BillDateInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_BillDateInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_DayImportHistoryFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser_StartDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_BillDateInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_DayImportHistoryTo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser_FinishDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_BillDateInfoLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jButton_Apply, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("Sum:");

        jLabel_Sum.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_Sum.setText("... VNĐ");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Promotion detail", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14), new java.awt.Color(153, 153, 153))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Promotion ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Username");

        jTextField_ID.setEditable(false);
        jTextField_ID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jTextField_User.setEditable(false);
        jTextField_User.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("Start Date");

        jTextField_StartDate.setEditable(false);
        jTextField_StartDate.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("Finish Date");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Products", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14), new java.awt.Color(153, 153, 153))); // NOI18N

        jTable_PromotionDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Percentage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_PromotionDetail);
        if (jTable_PromotionDetail.getColumnModel().getColumnCount() > 0) {
            jTable_PromotionDetail.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable_PromotionDetail.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextField_FinishDate.setEditable(false);
        jTextField_FinishDate.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jTextField_User)
                            .addComponent(jTextField_FinishDate)
                            .addComponent(jTextField_StartDate))))
                .addGap(73, 73, 73)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_FinishDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_Card1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Card1.setMaximumSize(new java.awt.Dimension(30000, 33));
        jPanel_Card1.setPreferredSize(new java.awt.Dimension(439, 30));
        jPanel_Card1.setLayout(new java.awt.GridLayout(1, 0, 35, 0));

        jButton_Add.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Add.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add30px.png"))); // NOI18N
        jButton_Add.setText("Add");
        jButton_Add.setFocusPainted(false);
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });
        jPanel_Card1.add(jButton_Add);

        jButton_Modify.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Modify.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Modify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        jButton_Modify.setText("Modify");
        jButton_Modify.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Modify.setEnabled(false);
        jButton_Modify.setMaximumSize(new java.awt.Dimension(95, 33));
        jButton_Modify.setMinimumSize(new java.awt.Dimension(95, 30));
        jButton_Modify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ModifyMouseClicked(evt);
            }
        });
        jButton_Modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModifyActionPerformed(evt);
            }
        });
        jPanel_Card1.add(jButton_Modify);

        jButton_Remove.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Remove.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        jButton_Remove.setText("Remove");
        jButton_Remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Remove.setEnabled(false);
        jButton_Remove.setMaximumSize(new java.awt.Dimension(123, 35));
        jButton_Remove.setMinimumSize(new java.awt.Dimension(95, 30));
        jButton_Remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_RemoveMouseClicked(evt);
            }
        });
        jButton_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemoveActionPerformed(evt);
            }
        });
        jPanel_Card1.add(jButton_Remove);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Search:");

        jTextField_NameSearch.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTextField_NameSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField_NameSearchCaretUpdate(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Status", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout(2, 2, 10, 0));

        jRadioButton_All.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton_All);
        jRadioButton_All.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jRadioButton_All.setSelected(true);
        jRadioButton_All.setText("All");
        jRadioButton_All.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton_AllStateChanged(evt);
            }
        });
        jPanel3.add(jRadioButton_All);

        jRadioButton_ComingSoon.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton_ComingSoon);
        jRadioButton_ComingSoon.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jRadioButton_ComingSoon.setText("Coming soon");
        jRadioButton_ComingSoon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton_ComingSoonStateChanged(evt);
            }
        });
        jPanel3.add(jRadioButton_ComingSoon);

        jRadioButton_Ongoing.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton_Ongoing);
        jRadioButton_Ongoing.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jRadioButton_Ongoing.setText("On-going");
        jRadioButton_Ongoing.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton_OngoingStateChanged(evt);
            }
        });
        jPanel3.add(jRadioButton_Ongoing);

        jRadioButton_Expired.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton_Expired);
        jRadioButton_Expired.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jRadioButton_Expired.setText("Expired");
        jRadioButton_Expired.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton_ExpiredStateChanged(evt);
            }
        });
        jPanel3.add(jRadioButton_Expired);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_ImportHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Sum, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_NameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel_BillDateInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(368, 368, 368)
                                        .addComponent(jPanel_Card1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(49, 49, 49)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_ImportHistory)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_BillDateInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_NameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel_Card1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_Sum))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ApplyActionPerformed
        // TODO add your handling code here:
        jRadioButton_All.setSelected(true);
        List<Promotion> list = prc.searchPromotions(jDateChooser_StartDate.getDate(), jDateChooser_FinishDate.getDate());
        prc.loadTable(list, dtmPromotion);
        jTextField_ID.setText("");
        jTextField_User.setText("");
        jTextField_StartDate.setText("");
        jTextField_FinishDate.setText("");
        dtmPromotionDetail.setRowCount(0);
    }//GEN-LAST:event_jButton_ApplyActionPerformed

    private void jTable_PromotionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_PromotionMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable_Promotion.convertRowIndexToModel(jTable_Promotion.getSelectedRow());
        String id = jTable_Promotion.getValueAt(selectedRow, 0).toString();

        jTextField_ID.setText(id);
        jTextField_User.setText(jTable_Promotion.getValueAt(selectedRow, 1).toString());
        jTextField_StartDate.setText(jTable_Promotion.getValueAt(selectedRow, 2).toString());
        jTextField_FinishDate.setText(jTable_Promotion.getValueAt(selectedRow, 3).toString());

        List<PromotionDetail> list = prc.getPromotionDetailByPromotionId(id);
        prc.loadProductTable(list, dtmPromotionDetail);
    }//GEN-LAST:event_jTable_PromotionMouseClicked

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        // TODO add your handling code here:
        loadData("all");
    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void jButton_ModifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ModifyMouseClicked
        // TODO add your handling code here:
        //        System.out.println("modify");
        //        mode = Mode.MODIFY;
        //        UIController.showCardLayout("cardSecond", jPanel_Card);
        //        setEditableForAll(true);
        //        jTable_Product.setEnabled(false);
    }//GEN-LAST:event_jButton_ModifyMouseClicked

    private void jButton_ModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModifyActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable_Promotion.convertRowIndexToModel(jTable_Promotion.getSelectedRow());
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "There is no selected promotion");
            return;
        }
        String id = jTextField_ID.getText();
        newPromotionDialog = new NewPromotionDialog(null, true, prc.getPromotionByID(id), prc.getPromotionDetailByPromotionId(id));

        newPromotionDialog.setVisible(true);
        jRadioButton_All.setSelected(true);
        jRadioButton_ComingSoon.setSelected(false);
        jRadioButton_Ongoing.setSelected(false);
        jRadioButton_Expired.setSelected(false);
        loadData("all");
    }//GEN-LAST:event_jButton_ModifyActionPerformed

    private void jButton_RemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RemoveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_RemoveMouseClicked

    private void jButton_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoveActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable_Promotion.convertRowIndexToModel(jTable_Promotion.getSelectedRow());
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "There is no selected promotion");
            return;
        }
        
        int luaChon = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove this product?");
        if (luaChon == JOptionPane.CANCEL_OPTION) {
            return;
        } else if (luaChon == JOptionPane.OK_OPTION) {
            Response response = prc.deletePromotionByID(jTextField_ID.getText());
            JOptionPane.showMessageDialog(this, prc.convertResponse(response.getMessage()).getMessage());
            if (response.getResponseCode() == 200) {
                jRadioButton_All.setSelected(true);
                loadData("all");
            } else {
                return;
            }
        }
    }//GEN-LAST:event_jButton_RemoveActionPerformed

    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed
        // TODO add your handling code here:
        newPromotionDialog = new NewPromotionDialog(null, true, null, null);

        newPromotionDialog.setVisible(true);
        jRadioButton_All.setSelected(true);
        jRadioButton_ComingSoon.setSelected(false);
        jRadioButton_Ongoing.setSelected(false);
        jRadioButton_Expired.setSelected(false);
        loadData("all");
    }//GEN-LAST:event_jButton_AddActionPerformed

    private void jTextField_NameSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField_NameSearchCaretUpdate
        // TODO add your handling code here:
        String tuKhoa = jTextField_NameSearch.getText();
        TableRowSorter<TableModel> trs = new TableRowSorter<>(jTable_Promotion.getModel());
        jTable_Promotion.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter("(?i)" + tuKhoa));
    }//GEN-LAST:event_jTextField_NameSearchCaretUpdate

    public void enableButton(boolean flag){
        jButton_Modify.setEnabled(flag);
        jButton_Remove.setEnabled(flag);
    }
    
    private void jRadioButton_AllStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton_AllStateChanged
        // TODO add your handling code here:

        if (jRadioButton_All.isSelected()) {
            jTextField_NameSearch.setText("");
            loadData("all");
            enableButton(false);
        }
    }//GEN-LAST:event_jRadioButton_AllStateChanged

    private void jRadioButton_ComingSoonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton_ComingSoonStateChanged
        // TODO add your handling code here:

        if (jRadioButton_ComingSoon.isSelected()) {
            jTextField_NameSearch.setText("");
            loadData("comingsoon");
            enableButton(true);
        }
    }//GEN-LAST:event_jRadioButton_ComingSoonStateChanged

    private void jRadioButton_OngoingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton_OngoingStateChanged
        // TODO add your handling code here:

        if (jRadioButton_Ongoing.isSelected()) {
            jTextField_NameSearch.setText("");
            loadData("ongoing");
            enableButton(false);
        }
    }//GEN-LAST:event_jRadioButton_OngoingStateChanged

    private void jRadioButton_ExpiredStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton_ExpiredStateChanged
        // TODO add your handling code here:

        if (jRadioButton_Expired.isSelected()) {
            jTextField_NameSearch.setText("");
            loadData("expired");
            enableButton(false);
        }
    }//GEN-LAST:event_jRadioButton_ExpiredStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Apply;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Modify;
    private javax.swing.JButton jButton_Remove;
    private com.toedter.calendar.JDateChooser jDateChooser_FinishDate;
    private com.toedter.calendar.JDateChooser jDateChooser_StartDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_DayImportHistoryFrom;
    private javax.swing.JLabel jLabel_DayImportHistoryTo;
    private javax.swing.JLabel jLabel_ImportHistory;
    private javax.swing.JLabel jLabel_Sum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_BillDateInfo;
    private javax.swing.JPanel jPanel_Card1;
    private javax.swing.JRadioButton jRadioButton_All;
    private javax.swing.JRadioButton jRadioButton_ComingSoon;
    private javax.swing.JRadioButton jRadioButton_Expired;
    private javax.swing.JRadioButton jRadioButton_Ongoing;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Promotion;
    private javax.swing.JTable jTable_PromotionDetail;
    private javax.swing.JTextField jTextField_FinishDate;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_NameSearch;
    private javax.swing.JTextField jTextField_StartDate;
    private javax.swing.JTextField jTextField_User;
    // End of variables declaration//GEN-END:variables
}
