/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.users;

import controller.AddressController;
import controller.UserController;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Vector;
import java.util.function.Function;
import java.util.stream.Collectors;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.Address;
import model.Province;
import model.Response;
import model.User;
import model.UserDB;
import okhttp3.MediaType;
import okhttp3.MultipartBody;
import okhttp3.RequestBody;
import okhttp3.ResponseBody;
import output.UserOutput;
import retrofit2.Call;
import retrofit2.Callback;
import service.APIClient;
import service.UploadFileService;
import swing.UIController;

/**
 *
 * @author Admin
 */
public class UserPanel extends javax.swing.JPanel {

    private static final String DEFAULT_IMAGE = "userDefaul.png";
    private DefaultTableModel dtm;
    private DefaultTableModel dtmShipper;
    private UserController uc;
    private AddressController ac;
    private UserOutput output;
    private String imageName;
    private Map<Integer, User> listUser;
    private List<UserDB> listShipper;
    private File selectedFile;

    private AddressDialog addressDialog;
    private UserDeletedDialog userDeletedDialog;

    private enum Mode {
        ADD,
        MODIFY,
        FREE
    }
    private Mode mode;
    /**
     * Creates new form StaffPanel
     */
    public UserPanel() {
        initComponents();
        dtm = (DefaultTableModel) jTable_User.getModel();
        dtmShipper = (DefaultTableModel) jTable_Shipper.getModel();
        uc = new UserController();
        ac = new AddressController();
        UIController.setDefaultTableHeader(jTable_User);
        UIController.setDefaultTableHeader(jTable_Shipper);
        loadData(1);
        loadShipper();
        loadProvince();
//        jButton_Remove.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_Customer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jTextField_Username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_LastName = new javax.swing.JTextField();
        jTextField_Address = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_FirstName = new javax.swing.JTextField();
        jTextField_NumOfOrders = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        jTextField_Phone = new javax.swing.JTextField();
        jButton_Detail = new javax.swing.JButton();
        jLabel_Image = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_Search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_User = new javax.swing.JTable();
        jButton_ExportExcel = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jComboBox_Address = new javax.swing.JComboBox<>();
        jButton_Deleted = new javax.swing.JButton();
        jButton_Remove = new javax.swing.JButton();
        jButton_PreviousPage = new javax.swing.JButton();
        jLabel_Page = new javax.swing.JLabel();
        jButton_NextPage = new javax.swing.JButton();
        jPanel_Staff = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField_ID1 = new javax.swing.JTextField();
        jTextField_Username1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_LastName1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_FirstName1 = new javax.swing.JTextField();
        jTextField_Email1 = new javax.swing.JTextField();
        jTextField_Phone1 = new javax.swing.JTextField();
        jButton_Detail1 = new javax.swing.JButton();
        jLabel_Image1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField_Search1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Shipper = new javax.swing.JTable();
        jButton_ExportExcel1 = new javax.swing.JButton();
        jPanel_Card = new javax.swing.JPanel();
        jPanel_Card1 = new javax.swing.JPanel();
        jButton_Add1 = new javax.swing.JButton();
        jButton_Modify1 = new javax.swing.JButton();
        jButton_Remove1 = new javax.swing.JButton();
        jPanel_Card2 = new javax.swing.JPanel();
        jButton_OK = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jButton_Clear = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        jPanel_Customer.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Customer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14), new java.awt.Color(153, 153, 153))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Username");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("Address");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setText("Email");

        jTextField_ID.setEditable(false);
        jTextField_ID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jTextField_Username.setEditable(false);
        jTextField_Username.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Name");

        jTextField_LastName.setEditable(false);
        jTextField_LastName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jTextField_Address.setEditable(false);
        jTextField_Address.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel18.setText("Image");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setText("Phone");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel11.setText("Number of orders");

        jTextField_FirstName.setEditable(false);
        jTextField_FirstName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jTextField_NumOfOrders.setEditable(false);
        jTextField_NumOfOrders.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jTextField_Email.setEditable(false);
        jTextField_Email.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jTextField_Phone.setEditable(false);
        jTextField_Phone.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jButton_Detail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/detail.png"))); // NOI18N
        jButton_Detail.setContentAreaFilled(false);
        jButton_Detail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DetailActionPerformed(evt);
            }
        });

        jLabel_Image.setText("image");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel14.setText("Search:");

        jTextField_Search.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTextField_Search.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField_SearchCaretUpdate(evt);
            }
        });

        jTable_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Last name", "First name", "Email", "Phone", "Province"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_UserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_User);
        if (jTable_User.getColumnModel().getColumnCount() > 0) {
            jTable_User.getColumnModel().getColumn(6).setHeaderValue("Province");
        }

        jButton_ExportExcel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_ExportExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excel.png"))); // NOI18N
        jButton_ExportExcel.setText("Export");
        jButton_ExportExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExportExcelActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel19.setText("Filter:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel21.setText("Address");

        jComboBox_Address.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jComboBox_Address.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_AddressItemStateChanged(evt);
            }
        });

        jButton_Deleted.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jButton_Deleted.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete_list.png"))); // NOI18N
        jButton_Deleted.setText("Deleted");
        jButton_Deleted.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Deleted.setFocusPainted(false);
        jButton_Deleted.setPreferredSize(new java.awt.Dimension(300, 60));
        jButton_Deleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeletedActionPerformed(evt);
            }
        });

        jButton_Remove.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Remove.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        jButton_Remove.setText("Remove");
        jButton_Remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Remove.setMaximumSize(new java.awt.Dimension(123, 35));
        jButton_Remove.setMinimumSize(new java.awt.Dimension(95, 30));
        jButton_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemoveActionPerformed(evt);
            }
        });

        jButton_PreviousPage.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_PreviousPage.setText("<");
        jButton_PreviousPage.setEnabled(false);
        jButton_PreviousPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PreviousPageActionPerformed(evt);
            }
        });

        jLabel_Page.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel_Page.setText("/");

        jButton_NextPage.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_NextPage.setText(">");
        jButton_NextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NextPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_CustomerLayout = new javax.swing.GroupLayout(jPanel_Customer);
        jPanel_Customer.setLayout(jPanel_CustomerLayout);
        jPanel_CustomerLayout.setHorizontalGroup(
            jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CustomerLayout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 104, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jButton_PreviousPage)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Page, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_NextPage)
                .addGap(18, 18, 18)
                .addComponent(jButton_ExportExcel)
                .addGap(18, 18, 18)
                .addComponent(jButton_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Deleted, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_CustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_CustomerLayout.createSequentialGroup()
                        .addGroup(jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_CustomerLayout.createSequentialGroup()
                                .addGroup(jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel_CustomerLayout.createSequentialGroup()
                                        .addGroup(jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel_CustomerLayout.createSequentialGroup()
                                                .addComponent(jTextField_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(107, 107, 107)
                                        .addGroup(jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel11))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_NumOfOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(jTextField_Phone))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel_CustomerLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(25, 25, 25)
                                .addComponent(jTextField_Address)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jButton_Detail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel_CustomerLayout.setVerticalGroup(
            jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CustomerLayout.createSequentialGroup()
                .addGroup(jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_CustomerLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField_NumOfOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Detail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))))
                    .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Deleted, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_ExportExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_PreviousPage)
                        .addComponent(jButton_NextPage)
                        .addComponent(jLabel_Page))
                    .addGroup(jPanel_CustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel19)
                        .addComponent(jLabel21)
                        .addComponent(jComboBox_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Customer", jPanel_Customer);

        jPanel_Staff.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Staff.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Staff information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14), new java.awt.Color(153, 153, 153))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("ID");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("Username");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel12.setText("Email");

        jTextField_ID1.setEditable(false);
        jTextField_ID1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jTextField_Username1.setEditable(false);
        jTextField_Username1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Name");

        jTextField_LastName1.setEditable(false);
        jTextField_LastName1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel20.setText("Image");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel13.setText("Phone");

        jTextField_FirstName1.setEditable(false);
        jTextField_FirstName1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jTextField_Email1.setEditable(false);
        jTextField_Email1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jTextField_Phone1.setEditable(false);
        jTextField_Phone1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jButton_Detail1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/detail.png"))); // NOI18N
        jButton_Detail1.setContentAreaFilled(false);
        jButton_Detail1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Detail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Detail1ActionPerformed(evt);
            }
        });

        jLabel_Image1.setText("image");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel16.setText("Search:");

        jTextField_Search1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTextField_Search1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField_Search1CaretUpdate(evt);
            }
        });

        jTable_Shipper.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Last name", "First name", "Email", "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Shipper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ShipperMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Shipper);

        jButton_ExportExcel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_ExportExcel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excel.png"))); // NOI18N
        jButton_ExportExcel1.setText("Export");
        jButton_ExportExcel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExportExcel1ActionPerformed(evt);
            }
        });

        jPanel_Card.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Card.setLayout(new java.awt.CardLayout());

        jPanel_Card1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Card1.setMaximumSize(new java.awt.Dimension(30000, 33));
        jPanel_Card1.setPreferredSize(new java.awt.Dimension(439, 30));
        jPanel_Card1.setLayout(new java.awt.GridLayout(1, 0, 35, 0));

        jButton_Add1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Add1.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Add1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add30px.png"))); // NOI18N
        jButton_Add1.setText("Add");
        jButton_Add1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add1.setMaximumSize(new java.awt.Dimension(95, 30));
        jButton_Add1.setMinimumSize(new java.awt.Dimension(95, 30));
        jButton_Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add1ActionPerformed(evt);
            }
        });
        jPanel_Card1.add(jButton_Add1);

        jButton_Modify1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Modify1.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Modify1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        jButton_Modify1.setText("Modify");
        jButton_Modify1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Modify1.setEnabled(false);
        jButton_Modify1.setMaximumSize(new java.awt.Dimension(95, 33));
        jButton_Modify1.setMinimumSize(new java.awt.Dimension(95, 30));
        jButton_Modify1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Modify1MouseClicked(evt);
            }
        });
        jButton_Modify1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Modify1ActionPerformed(evt);
            }
        });
        jPanel_Card1.add(jButton_Modify1);

        jButton_Remove1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Remove1.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Remove1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        jButton_Remove1.setText("Remove");
        jButton_Remove1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Remove1.setEnabled(false);
        jButton_Remove1.setMaximumSize(new java.awt.Dimension(123, 35));
        jButton_Remove1.setMinimumSize(new java.awt.Dimension(95, 30));
        jButton_Remove1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Remove1MouseClicked(evt);
            }
        });
        jButton_Remove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Remove1ActionPerformed(evt);
            }
        });
        jPanel_Card1.add(jButton_Remove1);

        jPanel_Card.add(jPanel_Card1, "cardFirst");

        jPanel_Card2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Card2.setLayout(new java.awt.GridLayout(1, 0, 35, 0));

        jButton_OK.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_OK.setForeground(new java.awt.Color(51, 51, 51));
        jButton_OK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add30px.png"))); // NOI18N
        jButton_OK.setText("OK");
        jButton_OK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OKActionPerformed(evt);
            }
        });
        jPanel_Card2.add(jButton_OK);

        jButton_Cancel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Cancel.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel20px.png"))); // NOI18N
        jButton_Cancel.setText("Cancel");
        jButton_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });
        jPanel_Card2.add(jButton_Cancel);

        jButton_Clear.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Clear.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clear.png"))); // NOI18N
        jButton_Clear.setText("Clear");
        jButton_Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });
        jPanel_Card2.add(jButton_Clear);

        jPanel_Card.add(jPanel_Card2, "cardSecond");

        javax.swing.GroupLayout jPanel_StaffLayout = new javax.swing.GroupLayout(jPanel_Staff);
        jPanel_Staff.setLayout(jPanel_StaffLayout);
        jPanel_StaffLayout.setHorizontalGroup(
            jPanel_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_StaffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel_StaffLayout.createSequentialGroup()
                        .addGroup(jPanel_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel_StaffLayout.createSequentialGroup()
                                .addGroup(jPanel_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Search1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel_StaffLayout.createSequentialGroup()
                                            .addGroup(jPanel_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField_ID1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField_Username1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(233, 233, 233)
                                            .addComponent(jLabel12)
                                            .addGap(4, 4, 4))
                                        .addGroup(jPanel_StaffLayout.createSequentialGroup()
                                            .addComponent(jTextField_LastName1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField_FirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel13))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Phone1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Email1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(243, 243, 243)
                        .addGroup(jPanel_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jButton_Detail1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel_Image1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 98, Short.MAX_VALUE))
                    .addGroup(jPanel_StaffLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_ExportExcel1)
                        .addGap(45, 45, 45)
                        .addComponent(jPanel_Card, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_StaffLayout.setVerticalGroup(
            jPanel_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_StaffLayout.createSequentialGroup()
                .addGroup(jPanel_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_StaffLayout.createSequentialGroup()
                        .addGroup(jPanel_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_StaffLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel20))
                            .addGroup(jPanel_StaffLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField_ID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_StaffLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(jTextField_Email1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel_StaffLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField_Username1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Detail1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_StaffLayout.createSequentialGroup()
                        .addGroup(jPanel_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Image1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_StaffLayout.createSequentialGroup()
                                .addGroup(jPanel_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextField_LastName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_FirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Phone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGap(24, 24, 24)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)))
                .addGroup(jPanel_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_ExportExcel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel_Card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Search1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Shipper", jPanel_Staff);

        add(jTabbedPane1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    public void clearAll() {
        jTextField_Username1.setText("");
        jTextField_FirstName1.setText("");
        jTextField_LastName1.setText("");
        jTextField_Email1.setText("");
        jTextField_ID1.setText("");
        jTextField_Phone1.setText("");
    }

    public void setEditableForAll(boolean editable) {
        jTextField_Username1.setEditable(editable);
        jTextField_FirstName1.setEditable(editable);
        jTextField_LastName1.setEditable(editable);
        jTextField_Email1.setEditable(editable);
        jTextField_Phone1.setEditable(editable);
    }
    
    public void loadShipper(){
        listShipper = uc.getUserByRole("shipper");
        Vector vt;
        dtmShipper.setNumRows(0);
        for (UserDB f : listShipper) {
            vt = new Vector();
            vt.add(f.getId());
            vt.add(f.getUsername());
            vt.add(f.getLastName());
            vt.add(f.getFirstName());
            vt.add(f.getEmail());
            vt.add(f.getPhone());
            dtmShipper.addRow(vt);
        }
    }
    
    public void loadProvince() {
        List<Province> list = ac.getAllProvince();
        jComboBox_Address.addItem(new Province("All"));
        for (Province p : list) {
            jComboBox_Address.addItem(p);
        }
    }

    private void loadData(int page) {
        output = uc.getUserInOnePage(page);
        jLabel_Page.setText(output.getPage() + "/" + output.getTotalPage());
        uc.loadTable(output.getListResult(), dtm);
        if (output.getPage() == 1) {
            jButton_PreviousPage.setEnabled(false);
        }
        if (output.getPage() == output.getTotalPage()) {
            jButton_NextPage.setEnabled(false);
        }
        listUser = output.getListResult().stream().collect(Collectors.toMap(User::getId, Function.identity()));
    }

    private void jTable_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_UserMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable_User.convertRowIndexToModel(jTable_User.getSelectedRow());
        if (selectedRow == -1) {
            return;
        }
        int id = Integer.parseInt(jTable_User.getValueAt(selectedRow, 0).toString());
        User u = listUser.get(id);

        jTextField_ID.setText(u.getId() + "");
        jTextField_Username.setText(u.getUsername());
        jTextField_LastName.setText(u.getLastName());
        jTextField_FirstName.setText(u.getFirstName());
        jTextField_Email.setText(u.getEmail());
        jTextField_Phone.setText(u.getPhone());
        jTextField_NumOfOrders.setText(u.getNumord() + "");
        Address address;
        if (u.getAddresses().isEmpty()) {
            jTextField_Address.setText("");
        } else {
            address = u.getAddresses().get(0);
            jTextField_Address.setText(address.getSpecificAddress() + ", " + address.getWard().getWardPrefix() + " " + address.getWard().getWardName() + ", " + address.getWard().getDistrict().getDistrictPrefix() + " " + address.getWard().getDistrict().getDistrictName() + ", " + address.getWard().getDistrict().getProvince().getProvinceName());
        }

        imageName = u.getImage();
        Image img = uc.getImage(imageName);
        Image newImg = img.getScaledInstance(jLabel_Image.getWidth(), jLabel_Image.getHeight(), java.awt.Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(newImg);
        jLabel_Image.setIcon(icon);

//        isSelected = true;
        jButton_Remove.setEnabled(true);
    }//GEN-LAST:event_jTable_UserMouseClicked

    private void jTextField_SearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField_SearchCaretUpdate
        // TODO add your handling code here:
        String tuKhoa = jTextField_Search.getText().toLowerCase();
        TableRowSorter<TableModel> trs = new TableRowSorter<>(jTable_User.getModel());
        jTable_User.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter("(?i)" + tuKhoa));
    }//GEN-LAST:event_jTextField_SearchCaretUpdate

    private void jButton_ExportExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExportExcelActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(false);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = fileChooser.showDialog(this, "Choose folder");
        if (x == JFileChooser.APPROVE_OPTION) {
            java.io.File file = fileChooser.getSelectedFile();
            utils.File.xuatFileExcel("UserList", (DefaultTableModel) jTable_User.getModel(), file.getAbsolutePath() + "/User");
            JOptionPane.showMessageDialog(this, "Export excel file successfully!");
        } else {
            return;
        }
    }//GEN-LAST:event_jButton_ExportExcelActionPerformed

    private void jButton_DeletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeletedActionPerformed
        // TODO add your handling code here:
        userDeletedDialog = new UserDeletedDialog(null, true);
        userDeletedDialog.setVisible(true);
    }//GEN-LAST:event_jButton_DeletedActionPerformed

    private void jButton_DetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DetailActionPerformed
        // TODO add your handling code here:
        if (!jTextField_ID.getText().equals("")) {
            List<Address> listAddress = new ArrayList<>();
            listAddress = listUser.get(Integer.valueOf(jTextField_ID.getText())).getAddresses();
            this.addressDialog = new AddressDialog(null, true, listAddress, this);
            this.addressDialog.setVisible(true);
        }
    }//GEN-LAST:event_jButton_DetailActionPerformed

    private void jButton_PreviousPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PreviousPageActionPerformed
        // TODO add your handling code here:
        if (output.getPage() > 1) {
            loadData(output.getPage() - 1);
            jButton_NextPage.setEnabled(true);
        }
        if (output.getPage() == 1) {
            jButton_PreviousPage.setEnabled(false);
        }
    }//GEN-LAST:event_jButton_PreviousPageActionPerformed

    private void jButton_NextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NextPageActionPerformed
        // TODO add your handling code here:
        if (output.getPage() < output.getTotalPage()) {
            loadData(output.getPage() + 1);
            jButton_PreviousPage.setEnabled(true);
        }
        if (output.getPage() == output.getTotalPage()) {
            jButton_NextPage.setEnabled(false);
        }
    }//GEN-LAST:event_jButton_NextPageActionPerformed

    private void jComboBox_AddressItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_AddressItemStateChanged
        // TODO add your handling code here:
        if (jComboBox_Address.getSelectedItem() == null) {
            return;
        }
        String provinceName = ((Province) jComboBox_Address.getSelectedItem()).getProvinceName();
        TableRowSorter<TableModel> trs = new TableRowSorter<>(jTable_User.getModel());
        jTable_User.setRowSorter(trs);
        if ("All".equals(jComboBox_Address.getSelectedItem().toString())) {
            return;
        }
        trs.setRowFilter(RowFilter.regexFilter("(?i)" + provinceName, 6));
    }//GEN-LAST:event_jComboBox_AddressItemStateChanged

    private void jButton_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoveActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable_User.getSelectedRow();
        if (selectedRow != -1) {
            int id = Integer.parseInt(jTable_User.getValueAt(selectedRow, 0).toString());
            User u = listUser.get(id);
            int luaChon = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove this user?", "OK", 0);
            if (luaChon == JOptionPane.CANCEL_OPTION) {
                return;
            } else if (luaChon == JOptionPane.OK_OPTION) {
                Response response = uc.updateStatusByID(u);
                JOptionPane.showMessageDialog(this, response.getMessage());
                if (response.getResponseCode() == 200) {
                    loadData(output.getPage());
                    jButton_Remove.setEnabled(false);
                } else {
                    return;
                }
            }
        }
    }//GEN-LAST:event_jButton_RemoveActionPerformed

    private void jButton_Detail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Detail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Detail1ActionPerformed

    private void jTextField_Search1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField_Search1CaretUpdate
        // TODO add your handling code here:
        String tuKhoa = jTextField_Search1.getText().toLowerCase();
        TableRowSorter<TableModel> trs = new TableRowSorter<>(jTable_Shipper.getModel());
        jTable_Shipper.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter("(?i)" + tuKhoa));
    }//GEN-LAST:event_jTextField_Search1CaretUpdate

    private void jTable_ShipperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ShipperMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable_Shipper.convertRowIndexToModel(jTable_Shipper.getSelectedRow());
        if (selectedRow == -1) {
            return;
        }
        int id = Integer.parseInt(jTable_Shipper.getValueAt(selectedRow, 0).toString());
        
        UserDB u = null;
        for (UserDB f : listShipper){
            if(f.getId() == id)
                u = f;
        }

        jTextField_ID1.setText(u.getId() + "");
        jTextField_Username1.setText(u.getUsername());
        jTextField_LastName1.setText(u.getLastName());
        jTextField_FirstName1.setText(u.getFirstName());
        jTextField_Email1.setText(u.getEmail());
        jTextField_Phone1.setText(u.getPhone());
        imageName = u.getImage();
        Image img = uc.getImage(u.getImage());
        Image newImg = img.getScaledInstance(jLabel_Image1.getWidth(), jLabel_Image1.getHeight(), java.awt.Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(newImg);
        jLabel_Image1.setIcon(icon);
        jButton_Modify1.setEnabled(true);
        jButton_Remove1.setEnabled(true);
    }//GEN-LAST:event_jTable_ShipperMouseClicked

    private void jButton_ExportExcel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExportExcel1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(false);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = fileChooser.showDialog(this, "Choose folder");
        if (x == JFileChooser.APPROVE_OPTION) {
            java.io.File file = fileChooser.getSelectedFile();
            utils.File.xuatFileExcel("ShipperList", (DefaultTableModel) jTable_Shipper.getModel(), file.getAbsolutePath() + "/Shipper");
            JOptionPane.showMessageDialog(this, "Export excel file successfully!");
        } else {
            return;
        }
    }//GEN-LAST:event_jButton_ExportExcel1ActionPerformed

    private void jButton_Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add1ActionPerformed
        // TODO add your handling code here:
        jTextField_ID.setText("");
        clearAll();
        mode = Mode.ADD;
        UIController.showCardLayout("cardSecond", jPanel_Card);
        setEditableForAll(true);
        jTable_Shipper.setEnabled(false);

        imageName = DEFAULT_IMAGE;
        Image img = uc.getImage(imageName);
        Image newImg = img.getScaledInstance(jLabel_Image1.getWidth(), jLabel_Image1.getHeight(), java.awt.Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(newImg);
        jLabel_Image1.setIcon(icon);
    }//GEN-LAST:event_jButton_Add1ActionPerformed

    private void jButton_Modify1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Modify1MouseClicked
        // TODO add your handling code here:
        //        System.out.println("modify");
        //        mode = Mode.MODIFY;
        //        UIController.showCardLayout("cardSecond", jPanel_Card);
        //        setEditableForAll(true);
        //        jTable_Product.setEnabled(false);
    }//GEN-LAST:event_jButton_Modify1MouseClicked

    private void jButton_Modify1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Modify1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable_Shipper.convertRowIndexToModel(jTable_Shipper.getSelectedRow());
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "There is no selected product");
            return;
        }

        System.out.println("modify");
        mode = Mode.MODIFY;
        UIController.showCardLayout("cardSecond", jPanel_Card);
        setEditableForAll(true);
        jTable_Shipper.setEnabled(false);
//        selectedProductId = jTextField_ID.getText();
//        selectedProductPrice = Float.parseFloat(jSpinner_Price.getValue().toString());
    }//GEN-LAST:event_jButton_Modify1ActionPerformed

    private void jButton_Remove1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Remove1MouseClicked
        // TODO add your handling code here:
        //        int luaChon = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove this product?");
        //        if (luaChon == JOptionPane.CANCEL_OPTION) {
            //            return;
            //        } else if (luaChon == JOptionPane.OK_OPTION) {
            //            Response response = pc.deleteProductByID(jTextField_ID.getText());
            //            JOptionPane.showMessageDialog(this, pc.convertResponse(response.getMessage()).getMessage());
            //            if (response.getResponseCode() == 200) {
                //                loadData(output.getPage());
                //                clearAll();
                //            } else {
                //                return;
                //            }
            //        }
    }//GEN-LAST:event_jButton_Remove1MouseClicked

    private void jButton_Remove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Remove1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable_Shipper.convertRowIndexToModel(jTable_Shipper.getSelectedRow());
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "There is no selected product");
            return;
        }

        int luaChon = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove this shipper?");
        if (luaChon == JOptionPane.CANCEL_OPTION) {
            return;
        } else if (luaChon == JOptionPane.OK_OPTION) {
            User u = new User();
            u.setId(Integer.parseInt(jTextField_ID.getText()));
            Response response = uc.updateStatusByID(u);
            JOptionPane.showMessageDialog(this, uc.convertResponse(response.getMessage()).getMessage());
            if (response.getResponseCode() == 200) {
                loadShipper();
                clearAll();
            } else {
                return;
            }
        }
    }//GEN-LAST:event_jButton_Remove1ActionPerformed

    private void jButton_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OKActionPerformed
        // TODO add your handling code here:
        String id = jTextField_ID1.getText();
        String username = jTextField_Username1.getText();
        String firstName = jTextField_FirstName1.getText();
        String lastName = jTextField_LastName1.getText();
        String email = jTextField_Email1.getText();
        String phone = jTextField_Phone1.getText();

        if (mode == Mode.ADD) {
            UserDB user = new UserDB();
            user.setUsername(username);
            user.setFirstName(firstName);
            user.setLastName(lastName);
            user.setEmail(email);
            user.setPhone(phone);
            user.setPassword(username);
            user.setStatus(true);
            Set<String> role = new HashSet<>();
            role.add("shipper");
            user.setRole(role);
            if (selectedFile != null) {
                try {
                    RequestBody requestBody = RequestBody.create(MediaType.parse("multipart/form-data"), selectedFile);
                    MultipartBody.Part part = MultipartBody.Part.createFormData("file", selectedFile.getName(), requestBody);
                    UploadFileService uploadFileInterface = APIClient.getClient().create(UploadFileService.class);
                    uploadFileInterface.uploadUserImage(part).enqueue(new Callback<ResponseBody>() {

                        @Override
                        public void onResponse(Call<ResponseBody> call, retrofit2.Response<ResponseBody> response) {
                            try {
                                if (response.isSuccessful()) {
                                    String str = response.body().string();
                                    user.setImage(str);
                                    System.out.println("vãi: " + user.getImage());
                                    Response res = uc.addShipper(user);
                                    JOptionPane.showMessageDialog(null, uc.convertResponse(res.getMessage()).getMessage());
                                    if (res.getResponseCode() == 200) {
                                        loadShipper();
                                        mode = Mode.FREE;
                                        UIController.showCardLayout("cardFirst", jPanel_Card);
                                        setEditableForAll(false);
                                        jTable_Shipper.setEnabled(true);
                                        selectedFile = null;
                                    } else {
                                        return;
                                    }
                                }
                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(null, e.getMessage());
                            }
                        }

                        @Override
                        public void onFailure(Call<ResponseBody> call, Throwable t) {
                            JOptionPane.showMessageDialog(null, t.getMessage());
                        }

                    });
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            } else {
                user.setImage(imageName);
                Response response = uc.addShipper(user);
                JOptionPane.showMessageDialog(this, uc.convertResponse(response.getMessage()).getMessage());
                if (response.getResponseCode() == 200) {
                    loadShipper();
                    mode = Mode.FREE;
                    UIController.showCardLayout("cardFirst", jPanel_Card);
                    setEditableForAll(false);
                    jTable_Shipper.setEnabled(true);
                    selectedFile = null;
                } else {
                    return;
                }
            }
        }
        if (mode == Mode.MODIFY) {
            UserDB user = new UserDB();
            user.setId(Long.parseLong(id));
            user.setUsername(username);
            user.setFirstName(firstName);
            user.setLastName(lastName);
            user.setEmail(email);
            user.setPhone(phone);
            if (selectedFile != null) {
                try {
                    RequestBody requestBody = RequestBody.create(MediaType.parse("multipart/form-data"), selectedFile);
                    MultipartBody.Part part = MultipartBody.Part.createFormData("file", selectedFile.getName(), requestBody);
                    UploadFileService uploadFileInterface = APIClient.getClient().create(UploadFileService.class);
                    uploadFileInterface.uploadProductImage(part).enqueue(new Callback<ResponseBody>() {

                        @Override
                        public void onResponse(Call<ResponseBody> call, retrofit2.Response<ResponseBody> response) {
                            try {
                                if (response.isSuccessful()) {
                                    String str = response.body().string();
                                    user.setImage(str);
                                    System.out.println("vãi: " + user.getImage());
                                    Response res = uc.updateUser(user);
                                    JOptionPane.showMessageDialog(null, uc.convertResponse(res.getMessage()).getMessage());
                                    if (res.getResponseCode() == 200) {
                                        loadShipper();
                                        mode = Mode.FREE;
                                        UIController.showCardLayout("cardFirst", jPanel_Card);
                                        setEditableForAll(false);
                                        jTable_Shipper.setEnabled(true);
                                        selectedFile = null;
                                    } else {
                                        return;
                                    }
                                }
                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(null, e.getMessage());
                            }
                        }

                        @Override
                        public void onFailure(Call<ResponseBody> call, Throwable t) {
                            JOptionPane.showMessageDialog(null, t.getMessage());
                        }

                    });
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            } else {
                user.setImage(imageName);
                Response response = uc.updateUser(user);
                JOptionPane.showMessageDialog(this, uc.convertResponse(response.getMessage()).getMessage());
                if (response.getResponseCode() == 200) {
                    loadShipper();
                    mode = Mode.FREE;
                    UIController.showCardLayout("cardFirst", jPanel_Card);
                    setEditableForAll(false);
                    jTable_Shipper.setEnabled(true);
                    selectedFile = null;
                } else {
                    return;
                }
            }
        }

    }//GEN-LAST:event_jButton_OKActionPerformed

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        // TODO add your handling code here:
        mode = Mode.FREE;
        clearAll();
        setEditableForAll(false);
        jTable_Shipper.setEnabled(true);

        UIController.showCardLayout("cardFirst", jPanel_Card);
        selectedFile = null;
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        // TODO add your handling code here:
        clearAll();
    }//GEN-LAST:event_jButton_ClearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add1;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Deleted;
    private javax.swing.JButton jButton_Detail;
    private javax.swing.JButton jButton_Detail1;
    private javax.swing.JButton jButton_ExportExcel;
    private javax.swing.JButton jButton_ExportExcel1;
    private javax.swing.JButton jButton_Modify1;
    private javax.swing.JButton jButton_NextPage;
    private javax.swing.JButton jButton_OK;
    private javax.swing.JButton jButton_PreviousPage;
    private javax.swing.JButton jButton_Remove;
    private javax.swing.JButton jButton_Remove1;
    private javax.swing.JComboBox<Province> jComboBox_Address;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JLabel jLabel_Image1;
    private javax.swing.JLabel jLabel_Page;
    private javax.swing.JPanel jPanel_Card;
    private javax.swing.JPanel jPanel_Card1;
    private javax.swing.JPanel jPanel_Card2;
    private javax.swing.JPanel jPanel_Customer;
    private javax.swing.JPanel jPanel_Staff;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_Shipper;
    private javax.swing.JTable jTable_User;
    private javax.swing.JTextField jTextField_Address;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_Email1;
    private javax.swing.JTextField jTextField_FirstName;
    private javax.swing.JTextField jTextField_FirstName1;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_ID1;
    private javax.swing.JTextField jTextField_LastName;
    private javax.swing.JTextField jTextField_LastName1;
    private javax.swing.JTextField jTextField_NumOfOrders;
    private javax.swing.JTextField jTextField_Phone;
    private javax.swing.JTextField jTextField_Phone1;
    private javax.swing.JTextField jTextField_Search;
    private javax.swing.JTextField jTextField_Search1;
    private javax.swing.JTextField jTextField_Username;
    private javax.swing.JTextField jTextField_Username1;
    // End of variables declaration//GEN-END:variables
}
