/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.products;

import controller.BrandController;
import controller.CategoryController;
import controller.PriceHistoryController;
import controller.ProductController;
import java.awt.Image;
import java.io.File;
import java.util.Enumeration;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.Brand;
import model.Category;
import model.PriceHistory;
import model.Product;
import model.Response;
import model.User;
import okhttp3.MediaType;
import okhttp3.MultipartBody;
import okhttp3.RequestBody;
import okhttp3.ResponseBody;
import output.ProductOutput;
import retrofit2.Call;
import retrofit2.Callback;
import service.APIClient;
import swing.UIController;
import service.UploadFileService;
import view.login.LoginFrame;

/**
 *
 * @author PC
 */
public class PanelProduct extends javax.swing.JPanel {

    public static String selectedProductId = "";
    public static String selectedProductName = "";
    private Float selectedProductPrice = (float)0.0;
    private static final String DEFAULT_IMAGE = "default.png";
    private DefaultTableModel dtm;
    private ProductController pc;
    private CategoryController cc;
    private BrandController bc;
    private PriceHistoryController phc;
    private ProductOutput output;
    private File selectedFile;
    private String imageName;
    private Boolean checkPrice = false;
    
    class Multi extends Thread {
        public void run() {
            while(true) {
                try {
                    sleep(2000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(PanelProduct.class.getName()).log(Level.SEVERE, null, ex);
                }
                loadData(output.getPage());
            }
        }
    }

    private enum Mode {
        ADD,
        MODIFY,
        FREE
    }
    private Mode mode;
    private NewCategoryDialog newCategoryDialog;
    private NewBrandDialog newBrandDialog;
    private FeedbackDialog feedbackDialog;
    private ProductDeletedDialog productDeletedDialog;
    private PriceHistoryDialog priceHistoryDialog;
    private ImportHistoryDialog importHistoryDialog;

    /**
     * Creates new form PanelProduct
     */
    public PanelProduct() {
        initComponents();
        jTextArea_Description.setWrapStyleWord(true);
        dtm = (DefaultTableModel) jTable_Product.getModel();
        pc = new ProductController();
        cc = new CategoryController();
        bc = new BrandController();
        phc = new PriceHistoryController();
        UIController.setDefaultTableHeader(jTable_Product);
        
        loadData(1);
        loadCategory();
        loadBrand();
        setEditableForAll(false);
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(jTable_Product.getModel());
        jTable_Product.setRowSorter(sorter);
        Multi t1 = new Multi();
        t1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jLabel_Category = new javax.swing.JLabel();
        jComboBox_Brand = new javax.swing.JComboBox<>();
        jComboBox_Category = new javax.swing.JComboBox<>();
        jTextField_Name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Unit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Specification = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSpinner_Price = new javax.swing.JSpinner();
        jSpinner_Quantity = new javax.swing.JSpinner();
        jSpinner_Discount = new javax.swing.JSpinner();
        jTextField_Sold = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_Description = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jButton_ChooseImage = new javax.swing.JButton();
        jButton_Category = new javax.swing.JButton();
        jButton_Brand = new javax.swing.JButton();
        jLabel_Image = new javax.swing.JLabel();
        jLabel_PriceHistory = new javax.swing.JLabel();
        jPanel_Card = new javax.swing.JPanel();
        jPanel_Card1 = new javax.swing.JPanel();
        jButton_Add = new javax.swing.JButton();
        jButton_Modify = new javax.swing.JButton();
        jButton_Remove = new javax.swing.JButton();
        jPanel_Card2 = new javax.swing.JPanel();
        jButton_OK = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jButton_Clear = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField_NameSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Product = new javax.swing.JTable();
        jButton_ExportExcel = new javax.swing.JButton();
        jButton_PreviousPage = new javax.swing.JButton();
        jButton_NextPage = new javax.swing.JButton();
        jLabel_Page = new javax.swing.JLabel();
        jButton_Feedback = new javax.swing.JButton();
        jButton_Refresh = new javax.swing.JButton();
        jButton_Feedback1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14), new java.awt.Color(153, 153, 153))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Name");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("Sold quantity");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setText("Price");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel13.setText("Brand");

        jTextField_ID.setEditable(false);
        jTextField_ID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTextField_ID.setEnabled(false);

        jLabel_Category.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_Category.setText("Category");

        jComboBox_Brand.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jComboBox_Category.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jTextField_Name.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("đ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Unit");

        jTextField_Unit.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("Specification");

        jTextField_Specification.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Discount");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel9.setText("Quantity");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("%");

        jSpinner_Price.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jSpinner_Price.setModel(new javax.swing.SpinnerNumberModel(10000, 0, null, 10000));

        jSpinner_Quantity.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jSpinner_Quantity.setModel(new javax.swing.SpinnerNumberModel(5, 1, null, 5));
        jSpinner_Quantity.setEnabled(false);

        jSpinner_Discount.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jSpinner_Discount.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 5));
        jSpinner_Discount.setEnabled(false);

        jTextField_Sold.setEditable(false);
        jTextField_Sold.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTextField_Sold.setEnabled(false);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel17.setText("Description");

        jTextArea_Description.setColumns(20);
        jTextArea_Description.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTextArea_Description.setLineWrap(true);
        jTextArea_Description.setRows(5);
        jScrollPane2.setViewportView(jTextArea_Description);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel18.setText("Image");

        jButton_ChooseImage.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_ChooseImage.setForeground(new java.awt.Color(51, 51, 51));
        jButton_ChooseImage.setText("Choose file");
        jButton_ChooseImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_ChooseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChooseImageActionPerformed(evt);
            }
        });

        jButton_Category.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Category.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jButton_Category.setMaximumSize(new java.awt.Dimension(35, 29));
        jButton_Category.setMinimumSize(new java.awt.Dimension(35, 29));
        jButton_Category.setPreferredSize(new java.awt.Dimension(35, 29));
        jButton_Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CategoryActionPerformed(evt);
            }
        });

        jButton_Brand.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Brand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        jButton_Brand.setMaximumSize(new java.awt.Dimension(35, 29));
        jButton_Brand.setMinimumSize(new java.awt.Dimension(35, 29));
        jButton_Brand.setPreferredSize(new java.awt.Dimension(35, 29));
        jButton_Brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BrandActionPerformed(evt);
            }
        });

        jLabel_Image.setText("image");

        jLabel_PriceHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/detail.png"))); // NOI18N
        jLabel_PriceHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_PriceHistoryMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Name)
                            .addComponent(jTextField_ID)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSpinner_Discount, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_PriceHistory)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinner_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_Unit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_Specification))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_Sold)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Category, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 73, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox_Brand, 0, 235, Short.MAX_VALUE)
                            .addComponent(jComboBox_Category, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_Category, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Brand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_ChooseImage, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(17, 17, 17)
                .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField_Unit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField_Specification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel_Category)
                                        .addComponent(jComboBox_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel18)
                                        .addComponent(jSpinner_Price))
                                    .addComponent(jSpinner_Discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 9, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel_PriceHistory, javax.swing.GroupLayout.Alignment.TRAILING))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9)
                                .addComponent(jSpinner_Quantity)
                                .addComponent(jTextField_Sold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(jComboBox_Brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_ChooseImage, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        jPanel_Card.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Card.setLayout(new java.awt.CardLayout());

        jPanel_Card1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Card1.setMaximumSize(new java.awt.Dimension(30000, 33));
        jPanel_Card1.setPreferredSize(new java.awt.Dimension(439, 30));
        jPanel_Card1.setLayout(new java.awt.GridLayout(1, 0, 35, 0));

        jButton_Add.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Add.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add30px.png"))); // NOI18N
        jButton_Add.setText("Add");
        jButton_Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add.setMaximumSize(new java.awt.Dimension(95, 30));
        jButton_Add.setMinimumSize(new java.awt.Dimension(95, 30));
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });
        jPanel_Card1.add(jButton_Add);

        jButton_Modify.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Modify.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Modify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        jButton_Modify.setText("Modify");
        jButton_Modify.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Modify.setEnabled(false);
        jButton_Modify.setMaximumSize(new java.awt.Dimension(95, 33));
        jButton_Modify.setMinimumSize(new java.awt.Dimension(95, 30));
        jButton_Modify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ModifyMouseClicked(evt);
            }
        });
        jButton_Modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModifyActionPerformed(evt);
            }
        });
        jPanel_Card1.add(jButton_Modify);

        jButton_Remove.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Remove.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        jButton_Remove.setText("Remove");
        jButton_Remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Remove.setEnabled(false);
        jButton_Remove.setMaximumSize(new java.awt.Dimension(123, 35));
        jButton_Remove.setMinimumSize(new java.awt.Dimension(95, 30));
        jButton_Remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_RemoveMouseClicked(evt);
            }
        });
        jButton_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemoveActionPerformed(evt);
            }
        });
        jPanel_Card1.add(jButton_Remove);

        jPanel_Card.add(jPanel_Card1, "cardFirst");

        jPanel_Card2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Card2.setLayout(new java.awt.GridLayout(1, 0, 35, 0));

        jButton_OK.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_OK.setForeground(new java.awt.Color(51, 51, 51));
        jButton_OK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add30px.png"))); // NOI18N
        jButton_OK.setText("OK");
        jButton_OK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OKActionPerformed(evt);
            }
        });
        jPanel_Card2.add(jButton_OK);

        jButton_Cancel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Cancel.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel20px.png"))); // NOI18N
        jButton_Cancel.setText("Cancel");
        jButton_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });
        jPanel_Card2.add(jButton_Cancel);

        jButton_Clear.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Clear.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clear.png"))); // NOI18N
        jButton_Clear.setText("Clear");
        jButton_Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });
        jPanel_Card2.add(jButton_Clear);

        jPanel_Card.add(jPanel_Card2, "cardSecond");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel14.setText("Search:");

        jTextField_NameSearch.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTextField_NameSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField_NameSearchCaretUpdate(evt);
            }
        });

        jTable_Product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Category", "Brand", "Unit", "Price", "Remain Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Product.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable_ProductFocusLost(evt);
            }
        });
        jTable_Product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Product);
        if (jTable_Product.getColumnModel().getColumnCount() > 0) {
            jTable_Product.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jButton_ExportExcel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_ExportExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excel.png"))); // NOI18N
        jButton_ExportExcel.setText("Export");
        jButton_ExportExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExportExcelActionPerformed(evt);
            }
        });

        jButton_PreviousPage.setText("<");
        jButton_PreviousPage.setEnabled(false);
        jButton_PreviousPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PreviousPageActionPerformed(evt);
            }
        });

        jButton_NextPage.setText(">");
        jButton_NextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NextPageActionPerformed(evt);
            }
        });

        jLabel_Page.setText("/");

        jButton_Feedback.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Feedback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tick3.png"))); // NOI18N
        jButton_Feedback.setText("Feedback");
        jButton_Feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FeedbackActionPerformed(evt);
            }
        });

        jButton_Refresh.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh30px.png"))); // NOI18N
        jButton_Refresh.setText("Refresh");
        jButton_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RefreshActionPerformed(evt);
            }
        });

        jButton_Feedback1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Feedback1.setText("Import History");
        jButton_Feedback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Feedback1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_NameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Feedback1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Refresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_ExportExcel)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_Card, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(31, 31, 31)
                        .addComponent(jButton_PreviousPage)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel_Page, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_NextPage)
                        .addGap(22, 22, 22)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel_Card, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_NameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(jButton_ExportExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Feedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_Feedback1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_PreviousPage)
                            .addComponent(jButton_NextPage)
                            .addComponent(jLabel_Page))
                        .addGap(26, 26, 26))))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void loadData(int page) {
        output = pc.getProductInOnePage(page);
        jLabel_Page.setText(output.getPage() + "/" + output.getTotalPage());
        pc.loadTable(output.getListResult(), dtm);
    }

    public void loadCategory() {
        jComboBox_Category.removeAllItems();
        List<Category> list = cc.getAllCategories();
        for (Category c : list) {
            jComboBox_Category.addItem(c);
        }
    }

    public void loadBrand() {
        jComboBox_Brand.removeAllItems();
        List<Brand> list = bc.getAllBrands();
        for (Brand b : list) {
            jComboBox_Brand.addItem(b);
        }
    }

    public void clearAll() {
        jTextField_Name.setText("");
        jTextArea_Description.setText("");
        jTextField_Unit.setText("");
        jTextField_Specification.setText("");
        jComboBox_Category.setSelectedIndex(-1);
        jComboBox_Brand.setSelectedIndex(-1);
        jSpinner_Quantity.setValue(0);
        jSpinner_Price.setValue(0);
        jSpinner_Discount.setValue(0);
    }

    public void setEditableForAll(boolean editable) {
        jTextField_Name.setEditable(editable);
        jTextArea_Description.setEditable(editable);
        jTextField_Unit.setEditable(editable);
        jTextField_Specification.setEditable(editable);
        jComboBox_Category.setEnabled(editable);
        jComboBox_Brand.setEnabled(editable);
        if(mode == Mode.MODIFY || mode == Mode.FREE)
            jSpinner_Quantity.setEnabled(editable);
        jSpinner_Price.setEnabled(editable);
//        jSpinner_Discount.setEnabled(editable);
        jTextField_NameSearch.setEnabled(!editable);
        jButton_ChooseImage.setEnabled(editable);
    }

    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }

    private void jButton_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OKActionPerformed
        // TODO add your handling code here:
        String name = jTextField_Name.getText();
        String unit = jTextField_Unit.getText();
        String specification = jTextField_Specification.getText();
        String description = jTextArea_Description.getText();
        float newPrice = Float.parseFloat(jSpinner_Price.getValue().toString());
        int discount = Integer.parseInt(jSpinner_Discount.getValue().toString());
        int soldQuantity = Integer.parseInt(jTextField_Sold.getText());
        int quantity = Integer.parseInt(jSpinner_Quantity.getValue().toString());

        Brand brand = (Brand) jComboBox_Brand.getSelectedItem();
        Category category = (Category) jComboBox_Category.getSelectedItem();
        
        if (mode == Mode.ADD) {
            Product product = new Product();
            product.setName(name);
            product.setDescription(description);
            product.setSpecification(specification);
            product.setCalculationUnit(unit);
            product.setDiscount(discount);
            product.setSoldQuantity(soldQuantity);
            product.setQuantity(quantity);
            product.setCategory(category);
            product.setBrand(brand);
            product.setStatus(true);
            if (selectedFile != null) {
                try {
                    RequestBody requestBody = RequestBody.create(MediaType.parse("multipart/form-data"), selectedFile);
                    MultipartBody.Part part = MultipartBody.Part.createFormData("file", selectedFile.getName(), requestBody);
                    UploadFileService uploadFileInterface = APIClient.getClient().create(UploadFileService.class);
                    uploadFileInterface.uploadProductImage(part).enqueue(new Callback<ResponseBody>() {

                        @Override
                        public void onResponse(Call<ResponseBody> call, retrofit2.Response<ResponseBody> response) {
                            try {
                                if (response.isSuccessful()) {
                                    String str = response.body().string();
                                    product.setImage(str);
                                    System.out.println("vãi: " + product.getImage());
                                    Response res = pc.addProduct(product, newPrice);
                                    JOptionPane.showMessageDialog(null, pc.convertResponse(res.getMessage()).getMessage());
                                    if (res.getResponseCode() == 200) {
                                        loadData(output.getPage());
                                        mode = Mode.FREE;
                                        UIController.showCardLayout("cardFirst", jPanel_Card);
                                        setEditableForAll(false);
                                        jTable_Product.setEnabled(true);
                                        selectedFile = null;
                                    } else {
                                        return;
                                    }
                                }
                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(null, e.getMessage());
                            }
                        }

                        @Override
                        public void onFailure(Call<ResponseBody> call, Throwable t) {
                            JOptionPane.showMessageDialog(null, t.getMessage());
                        }

                    });
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            } else {
                product.setImage(imageName);
                Response response = pc.addProduct(product, newPrice);
                JOptionPane.showMessageDialog(this, pc.convertResponse(response.getMessage()).getMessage());
                if (response.getResponseCode() == 200) {
                    loadData(output.getPage());
                    mode = Mode.FREE;
                    UIController.showCardLayout("cardFirst", jPanel_Card);
                    setEditableForAll(false);
                    jTable_Product.setEnabled(true);
                    selectedFile = null;
                } else {
                    return;
                }
            }
        }
        if (mode == Mode.MODIFY) {
            float lastedImportPrice = pc.getLastedImportPrice(jTextField_ID.getText());
            if(newPrice <= lastedImportPrice) {
                int luaChon = JOptionPane.showConfirmDialog(this, "Giá bán nhỏ hơn/bằng giá nhập hàng mới nhất (" + lastedImportPrice + "), bạn có chắc chắn muốn lưu?");
                if (luaChon == JOptionPane.CANCEL_OPTION || luaChon == JOptionPane.NO_OPTION) 
                    return;
            }
            Product product = new Product();
            product.setProductId(Integer.parseInt(jTextField_ID.getText()));
            product.setName(name);
            product.setDescription(description);
            product.setSpecification(specification);
            product.setCalculationUnit(unit);
            product.setDiscount(discount);
            product.setSoldQuantity(soldQuantity);
            product.setQuantity(quantity);
            product.setCategory(category);
            product.setBrand(brand);
            product.setStatus(true);
            if (selectedFile != null) {
                try {
                    RequestBody requestBody = RequestBody.create(MediaType.parse("multipart/form-data"), selectedFile);
                    MultipartBody.Part part = MultipartBody.Part.createFormData("file", selectedFile.getName(), requestBody);
                    UploadFileService uploadFileInterface = APIClient.getClient().create(UploadFileService.class);
                    uploadFileInterface.uploadProductImage(part).enqueue(new Callback<ResponseBody>() {

                        @Override
                        public void onResponse(Call<ResponseBody> call, retrofit2.Response<ResponseBody> response) {
                            try {
                                if (response.isSuccessful()) {
                                    String str = response.body().string();
                                    product.setImage(str);
                                    System.out.println("vãi: " + product.getImage());
                                    Response res = pc.updateProductByID(product.getProductId(), newPrice, product);
                                    JOptionPane.showMessageDialog(null, pc.convertResponse(res.getMessage()).getMessage());
                                    if (res.getResponseCode() == 200) {
                                        loadData(output.getPage());
                                        mode = Mode.FREE;
                                        UIController.showCardLayout("cardFirst", jPanel_Card);
                                        setEditableForAll(false);
                                        jTable_Product.setEnabled(true);
                                        selectedFile = null;
                                    } else {
                                        return;
                                    }
                                }
                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(null, e.getMessage());
                            }
                        }

                        @Override
                        public void onFailure(Call<ResponseBody> call, Throwable t) {
                            JOptionPane.showMessageDialog(null, t.getMessage());
                        }

                    });
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            } else {
                product.setImage(imageName);
                Response response = pc.updateProductByID(product.getProductId(), newPrice, product);
                JOptionPane.showMessageDialog(this, pc.convertResponse(response.getMessage()).getMessage());
                if (response.getResponseCode() == 200) {
                    loadData(output.getPage());
                    mode = Mode.FREE;
                    UIController.showCardLayout("cardFirst", jPanel_Card);
                    setEditableForAll(false);
                    jTable_Product.setEnabled(true);
                    selectedFile = null;
                } else {
                    return;
                }
            }
        }
        
    }//GEN-LAST:event_jButton_OKActionPerformed

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        // TODO add your handling code here:
        mode = Mode.FREE;
        clearAll();
        setEditableForAll(false);
        jTable_Product.setEnabled(true);

        UIController.showCardLayout("cardFirst", jPanel_Card);
        selectedFile = null;
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        // TODO add your handling code here:
        clearAll();
    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed
        // TODO add your handling code here:
        jTextField_ID.setText("");
        clearAll();
        mode = Mode.ADD;
        UIController.showCardLayout("cardSecond", jPanel_Card);
        setEditableForAll(true);
        jTable_Product.setEnabled(false);
        jTextField_Sold.setText("0");

        imageName = DEFAULT_IMAGE;
        Image img = pc.getImage(imageName);
        Image newImg = img.getScaledInstance(jLabel_Image.getWidth(), jLabel_Image.getHeight(), java.awt.Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(newImg);
        jLabel_Image.setIcon(icon);
    }//GEN-LAST:event_jButton_AddActionPerformed

    private void jTable_ProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ProductMouseClicked
        // TODO add your handling code here:
        if (mode == Mode.ADD || mode == Mode.MODIFY) {
            return;
        }
        int selectedRow = jTable_Product.convertRowIndexToModel(jTable_Product.getSelectedRow());

        Product p = pc.getProductById(dtm.getValueAt(selectedRow, 0).toString());
        jTextField_ID.setText(p.getProductId() + "");
        jTextField_Name.setText(p.getName());
        jTextField_Unit.setText(p.getCalculationUnit());
        jTextField_Specification.setText(p.getSpecification());
        jTextField_Sold.setText(p.getSoldQuantity() + "");
        jTextArea_Description.setText(p.getDescription());

        for (int i = 0; i < jComboBox_Brand.getItemCount(); i++) {
            if (jComboBox_Brand.getItemAt(i).getBrandId().equals(p.getBrand().getBrandId())) {
                jComboBox_Brand.setSelectedIndex(i);
            }
        }

        for (int i = 0; i < jComboBox_Category.getItemCount(); i++) {
            if (jComboBox_Category.getItemAt(i).getCategoryId().equals(p.getCategory().getCategoryId())) {
                jComboBox_Category.setSelectedIndex(i);
            }
        }

        imageName = p.getImage();
        Image img = pc.getImage(imageName);
        Image newImg = img.getScaledInstance(jLabel_Image.getWidth(), jLabel_Image.getHeight(), java.awt.Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(newImg);
        jLabel_Image.setIcon(icon);

        jSpinner_Price.setValue(p.getPrice());
        jSpinner_Discount.setValue(p.getDiscount());
        jSpinner_Quantity.setValue(p.getQuantity());
        jButton_Modify.setEnabled(true);
        jButton_Remove.setEnabled(true);
    }//GEN-LAST:event_jTable_ProductMouseClicked

    private void jTextField_NameSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField_NameSearchCaretUpdate
        // TODO add your handling code here:
        String tuKhoa = jTextField_NameSearch.getText();
        TableRowSorter<TableModel> trs = new TableRowSorter<>(jTable_Product.getModel());
        jTable_Product.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter("(?i)" + tuKhoa));
    }//GEN-LAST:event_jTextField_NameSearchCaretUpdate

    private void jButton_ExportExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExportExcelActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(false);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = fileChooser.showDialog(this, "Choose folder");
        if (x == JFileChooser.APPROVE_OPTION) {
            java.io.File file = fileChooser.getSelectedFile();
            utils.File.xuatFileExcel("ProductList", (DefaultTableModel) jTable_Product.getModel(), file.getAbsolutePath() + "/Product");
            JOptionPane.showMessageDialog(this, "Export excel file successfully!");
        }
        else {
            return;
        }
    }//GEN-LAST:event_jButton_ExportExcelActionPerformed

    private void jButton_ChooseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChooseImageActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Image Files", "jpg", "png");
        fileChooser.setFileFilter(imageFilter);
        fileChooser.setMultiSelectionEnabled(false);
        int x = fileChooser.showDialog(this, "Select image");
        if (x == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();
            ImageIcon imgIcon = new ImageIcon(selectedFile.getAbsolutePath());
            Image img = imgIcon.getImage();
            Image newImg = img.getScaledInstance(jLabel_Image.getWidth(), jLabel_Image.getHeight(), java.awt.Image.SCALE_SMOOTH);
            jLabel_Image.setIcon(new ImageIcon(newImg));
            System.out.println(selectedFile.getName());
        } else {
            return;
        }
    }//GEN-LAST:event_jButton_ChooseImageActionPerformed

    private void jButton_NextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NextPageActionPerformed
        // TODO add your handling code here:
        if (output.getPage() < output.getTotalPage()) {
            loadData(output.getPage() + 1);
            jButton_PreviousPage.setEnabled(true);
        }
        if (output.getPage() == output.getTotalPage())
            jButton_NextPage.setEnabled(false);
    }//GEN-LAST:event_jButton_NextPageActionPerformed

    private void jButton_PreviousPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PreviousPageActionPerformed
        // TODO add your handling code here:
        if (output.getPage() > 1) {
            loadData(output.getPage() - 1);
            jButton_NextPage.setEnabled(true);
        }
        if (output.getPage() == 1)
            jButton_PreviousPage.setEnabled(false);
    }//GEN-LAST:event_jButton_PreviousPageActionPerformed

    private void jTable_ProductFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable_ProductFocusLost
        // TODO add your handling code here:
//        jButton_Modify.setEnabled(false);
//        jButton_Remove.setEnabled(false);
    }//GEN-LAST:event_jTable_ProductFocusLost

    private void jButton_ModifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ModifyMouseClicked
        // TODO add your handling code here:
//        System.out.println("modify");
//        mode = Mode.MODIFY;
//        UIController.showCardLayout("cardSecond", jPanel_Card);
//        setEditableForAll(true);
//        jTable_Product.setEnabled(false);
    }//GEN-LAST:event_jButton_ModifyMouseClicked

    private void jButton_RemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RemoveMouseClicked
        // TODO add your handling code here:
//        int luaChon = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove this product?");
//        if (luaChon == JOptionPane.CANCEL_OPTION) {
//            return;
//        } else if (luaChon == JOptionPane.OK_OPTION) {
//            Response response = pc.deleteProductByID(jTextField_ID.getText());
//            JOptionPane.showMessageDialog(this, pc.convertResponse(response.getMessage()).getMessage());
//            if (response.getResponseCode() == 200) {
//                loadData(output.getPage());
//                clearAll();
//            } else {
//                return;
//            }
//        }
    }//GEN-LAST:event_jButton_RemoveMouseClicked

    private void jButton_ModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModifyActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable_Product.convertRowIndexToModel(jTable_Product.getSelectedRow());
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "There is no selected product");
            return;
        }
        
        System.out.println("modify");
        mode = Mode.MODIFY;
        UIController.showCardLayout("cardSecond", jPanel_Card);
        setEditableForAll(true);
        jTable_Product.setEnabled(false);
        selectedProductId = jTextField_ID.getText();
        selectedProductPrice = Float.parseFloat(jSpinner_Price.getValue().toString());
    }//GEN-LAST:event_jButton_ModifyActionPerformed

    private void jButton_CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CategoryActionPerformed
        // TODO add your handling code here:
        newCategoryDialog = new NewCategoryDialog(null, true, this);

        newCategoryDialog.setVisible(true);
        loadCategory();
    }//GEN-LAST:event_jButton_CategoryActionPerformed

    private void jButton_BrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BrandActionPerformed
        // TODO add your handling code here:
        newBrandDialog = new NewBrandDialog(null, true, this);
        
        newBrandDialog.setVisible(true);
        loadBrand();
    }//GEN-LAST:event_jButton_BrandActionPerformed

    private void jButton_FeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FeedbackActionPerformed
        // TODO add your handling code here:
        String str = jTextField_ID.getText();
        if(str.equals("")) {
            JOptionPane.showMessageDialog(this, "No product selected");
            return;
        }
        selectedProductId = str;
        selectedProductName = jTextField_Name.getText();
            
        feedbackDialog = new FeedbackDialog(null, true);
        
        feedbackDialog.setVisible(true);
    }//GEN-LAST:event_jButton_FeedbackActionPerformed

    private void jButton_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoveActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable_Product.convertRowIndexToModel(jTable_Product.getSelectedRow());
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "There is no selected product");
            return;
        }
        
        int luaChon = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove this product?");
        if (luaChon == JOptionPane.CANCEL_OPTION) {
            return;
        } else if (luaChon == JOptionPane.OK_OPTION) {
            Response response = pc.deleteProductByID(jTextField_ID.getText());
            JOptionPane.showMessageDialog(this, pc.convertResponse(response.getMessage()).getMessage());
            if (response.getResponseCode() == 200) {
                loadData(output.getPage());
                clearAll();
            } else {
                return;
            }
        }
    }//GEN-LAST:event_jButton_RemoveActionPerformed

    private void jLabel_PriceHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PriceHistoryMouseClicked
        // TODO add your handling code here:
        String str = jTextField_ID.getText();
        if(str.equals("")) {
            JOptionPane.showMessageDialog(this, "No product selected");
            return;
        }
        selectedProductId = str;
        selectedProductName = jTextField_Name.getText();
            
        priceHistoryDialog = new PriceHistoryDialog(null, true);
        
        priceHistoryDialog.setVisible(true);
    }//GEN-LAST:event_jLabel_PriceHistoryMouseClicked

    private void jButton_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RefreshActionPerformed
        // TODO add your handling code here:
        loadData(output.getPage());
    }//GEN-LAST:event_jButton_RefreshActionPerformed

    private void jButton_Feedback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Feedback1ActionPerformed
        // TODO add your handling code here:
        String str = jTextField_ID.getText();
        if(str.equals("")) {
            JOptionPane.showMessageDialog(this, "No product selected");
            return;
        }
        selectedProductId = str;
        selectedProductName = jTextField_Name.getText();
        
        importHistoryDialog = new ImportHistoryDialog(null, true);
        importHistoryDialog.setVisible(true);
    }//GEN-LAST:event_jButton_Feedback1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Brand;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Category;
    private javax.swing.JButton jButton_ChooseImage;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_ExportExcel;
    private javax.swing.JButton jButton_Feedback;
    private javax.swing.JButton jButton_Feedback1;
    private javax.swing.JButton jButton_Modify;
    private javax.swing.JButton jButton_NextPage;
    private javax.swing.JButton jButton_OK;
    private javax.swing.JButton jButton_PreviousPage;
    private javax.swing.JButton jButton_Refresh;
    private javax.swing.JButton jButton_Remove;
    private javax.swing.JComboBox<Brand> jComboBox_Brand;
    private javax.swing.JComboBox<Category> jComboBox_Category;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Category;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JLabel jLabel_Page;
    private javax.swing.JLabel jLabel_PriceHistory;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Card;
    private javax.swing.JPanel jPanel_Card1;
    private javax.swing.JPanel jPanel_Card2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner_Discount;
    private javax.swing.JSpinner jSpinner_Price;
    private javax.swing.JSpinner jSpinner_Quantity;
    private javax.swing.JTable jTable_Product;
    private javax.swing.JTextArea jTextArea_Description;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_NameSearch;
    private javax.swing.JTextField jTextField_Sold;
    private javax.swing.JTextField jTextField_Specification;
    private javax.swing.JTextField jTextField_Unit;
    // End of variables declaration//GEN-END:variables
}
